require 'rubygems'
require 'rake/clean'

def run(command)
  puts command
  system command
  puts
end

latex_file_name = "computational-learning-theory"

task :rebuild do
	run("pdflatex #{latex_file_name}")
	run("bibtex #{latex_file_name}")
	run("pdflatex #{latex_file_name}")
	run("pdflatex #{latex_file_name}")
end

task :build do	
	run("pdflatex #{latex_file_name}")
end

task :default => [:build]
